FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

RUN apt-get update

RUN apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs

WORKDIR /app

RUN dotnet tool install -g dotnet-watch

